# -*- coding: utf-8 -*-
"""Structured content for the capstone audit PDF (v3.0 — post-audit & optimizations)."""

PROJECT = {
    "title": "PCSPF Pancreatic Cancer Survival — Project Audit Documentation",
    "subtitle": "Complete Technical Record, Methodology Audit, and Plain-Language Companion",
    "course": "Fundamentals of Data Science — CMSC 176",
    "institution": "University of the Philippines Manila",
    "notebook": "PCSPF_Data_Science_Capstone.ipynb",
    "data_file": "Dataset/PCSPF-Pancreatic Cancer Survival based on Preoperative Features.xlsx",
    "n_patients": 878,
    "n_features": 20,
    "n_cells": 171,
    "n_sections": 9,
    "random_state": 42,
    "optimal_k": 3,
    "version": "3.2",
}

RESULTS = {
    "baseline_acc": "68.8%",
    "untuned_acc": "68.18%",
    "tuned_acc": "61.93%",
    "train_acc": "85.8%",
    "overfit_gap": "23.8 pp",
    "improvement_pp": "-6.87",
    "auc": "0.563",
    "macro_f1": "0.550",
    "cv_f1_binary": "0.809 (legacy f1 row)",
    "cv_f1_macro": "0.579",
    "chi2_p": "0.2546",
    "cramers_v": "0.048",
    "pca_var_pc1": "20.3%",
    "pca_var_pc2": "10.5%",
    "pca_var_cumulative": "30.8%",
    "top_features": ["CA19-9", "CEA", "Prealbumin", "CRP/ALB", "BMI"],
    "best_rf_params": {
        "n_estimators": 100,
        "max_depth": 5,
        "min_samples_split": 10,
        "min_samples_leaf": 4,
    },
    "clusters": [
        ("0", "519", "59.1%", "70.1%", "Lower inflammation; higher prealbumin/ALB"),
        ("1", "204", "23.2%", "69.6%", "Elevated bilirubin, NLR, SII; lower prealbumin"),
        ("2", "155", "17.7%", "63.2%", "Highest CRP/CRP/ALB; more abdominal pain"),
    ],
    "model_comparison": [
        ("Random Forest (f1_macro tuned)", "61.9%", "0.550", "0.563", "Yes (Gini)", "85.8% train — reduced overfit vs legacy"),
        ("Logistic Regression", "55.1%", "0.539", "0.599", "No (needs SHAP)", "Highest class-0 recall (61.8%)"),
        ("SVM RBF", "61.9%", "0.590", "0.622", "No (needs SHAP)", "Best macro F1 & AUC"),
        ("Gradient Boosting", "63.6%", "0.482", "0.581", "Yes (Gini)", "High train acc — overfits"),
    ],
    "unsup_comparison_k3": [
        ("K-Means", "Highest silhouette", "p=0.2546", "100% assigned", "Yes — centroids"),
        ("GMM", "Lower silhouette", "p≈0.53", "100% assigned", "Yes — means"),
        ("Agglomerative Ward", "Mid silhouette", "p≈0.65", "100% assigned", "No centroids"),
        ("DBSCAN (best sig.)", "Outlier pockets", "p<0.01", "~49% assigned", "No — noise labels"),
    ],
}

FIGURES = [
    ("1", "target_distribution.png", "3.2", "Bar chart of class 0 vs class 1 with count and percent labels"),
    ("2", "feature_distributions.png", "3.3", "4×5 grid of histograms + KDE for 18 continuous features"),
    ("3", "boxplots_by_survival.png", "3.4", "Boxplots of each continuous feature by survival label"),
    ("4", "correlation_heatmap.png", "3.5", "Lower-triangle Pearson correlation heatmap (20 features + target)"),
    ("5", "class_conditional_means.png", "3.7", "Horizontal bar chart of top 10 mean differences by class"),
    ("6", "outlier_boxplots.png", "4.4", "Per-feature z-score boxplots for outlier comparison"),
    ("7", "preprocessing_summary.png", "4.10", "Table figure of all preprocessing decisions"),
    ("8", "scaling_before_after.png", "5.3", "Side-by-side boxplots before/after StandardScaler"),
    ("9", "unsupervised_model_comparison.png", "6.0", "K-Means vs GMM vs Ward at k=3 (silhouette, chi-sq p, spread)"),
    ("10", "elbow_method.png", "6.1", "Line plot of inertia vs k (2–10) with elbow marker"),
    ("11", "silhouette_scores.png", "6.2", "Line plot of mean silhouette vs k"),
    ("12", "pca_clusters.png", "6.5", "2D PCA scatter colored by cluster + centroids"),
    ("13", "cluster_profiles_heatmap.png", "6.6", "Heatmap of z-scored mean features per cluster"),
    ("14", "cluster_survival_overlay.png", "6.7", "Grouped bar chart of survival counts per cluster"),
    ("15", "pca_survival_labels.png", "6.8", "2D PCA scatter colored by true survival"),
    ("16", "confusion_matrix.png", "7.3", "Seaborn heatmap of tuned RF predictions"),
    ("17", "roc_curve.png", "7.3", "ROC with AUC annotation and diagonal reference"),
    ("18", "classification_report.png", "7.3", "Tabular precision/recall/F1 figure"),
    ("19", "feature_importance.png", "7.4", "Horizontal bar chart of all 20 Gini importances"),
    ("20", "supervised_model_comparison.png", "7.5", "RF vs LR vs SVM vs GB — accuracy, macro F1, AUC"),
    ("21", "synthesis_comparison.png", "8.1", "Side-by-side top-10 RF vs cluster-differentiation"),
]

AUDIT_ENHANCEMENTS = [
    ("Section 2", "Pre-standardized data note",
     "Documented that 18 continuous features in the released file are already z-scored (mean≈0, std≈1).",
     "Clarifies why EDA ranges look standardized and why additional scaling is only emphasized for K-Means."),
    ("Section 6.5", "PCA variance caveat",
     "Added explicit note: PC1+PC2 = 30.8% variance; 69.2% of structure not visible in 2D plots.",
     "Prevents over-interpretation of PCA overlap as proof clusters are meaningless."),
    ("Section 6.7", "Cramér's V effect size",
     "Computed Cramér's V ≈ 0.048 alongside chi-square p=0.2546.",
     "Shows association is not only non-significant but also negligible in effect size."),
    ("Section 7.2", "Three-objective RF tuning",
     "Compared f1 (legacy grid), f1_macro (primary), recall_macro (stretch) with regularized hyperparameter grid.",
     "Aligns tuning with macro F1 evaluation; documents legacy f1 row for before/after comparison."),
    ("Section 7.2", "Threshold sweep",
     "Exploratory probability threshold sweep on primary f1_macro model (default 0.50 retained).",
     "Shows accuracy/recall trade-off without re-tuning on test labels."),
    ("Section 7.3", "Train vs test overfitting table",
     "Primary f1_macro RF: 85.8% train vs 61.93% test (23.8 pp gap) vs legacy f1 (100% / 71.02% / 29 pp).",
     "Documents reduced memorization after macro-aligned tuning."),
    ("Section 7.3", "Regularized RF comparison",
     "Compared depth/leaf constraints showing accuracy–generalization trade-off.",
     "Demonstrates regularization reduces overfit but does not reach clinical AUC threshold."),
    ("Section 7.3", "Class-0 recall interpretation",
     "Confusion matrix shows low recall for shorter-survival class (minority).",
     "Clinical framing: model misses many high-risk patients despite balanced weights."),
    ("Section 7.5", "Enhanced supervised model comparison",
     "Benchmarked RF, LR, SVM RBF, GB with train/test gap, macro F1, AUC, CV macro F1.",
     "Justifies RF retention on interpretability despite SVM's higher balanced metrics."),
    ("Section 6 (top)", "Unsupervised method comparison",
     "K-Means, GMM, Ward, DBSCAN compared on silhouette, chi-sq, cluster balance, assignment.",
     "Justifies K-Means: best silhouette at k=3, full assignment, interpretable centroids."),
    ("Section 7 (top)", "Why Random Forest?",
     "Five-factor justification: non-linear interactions, Gini importance, multicollinearity, no scaling, course scope.",
     "Pre-empts defense questions before baseline model section."),
]

PREPROCESSING_DECISIONS = [
    ("Drop ID, Predict labels", "Removed", "ID anonymized; predict columns 100% NaN"),
    ("Missing values", "No imputation", "Zero nulls after column drop"),
    ("Duplicates", "None removed", "0 duplicate rows"),
    ("Outliers", "Retained", "Clinically meaningful extremes; IQR documented"),
    ("Normality transform", "Not applied", "RF rank-invariant; scaler for K-Means only"),
    ("Multicollinearity (VIF)", "Retain all features", "RF subsampling; ratio features clinically validated"),
    ("Feature engineering", "None added", "NLR, PLR, SII, CRP/ALB already in dataset"),
    ("Feature selection", "All 20 retained", "Post-hoc RF importance; same set for K-Means"),
    ("SMOTE", "Not used", "class_weight='balanced' preferred for clinical defensibility"),
    ("RF scaling", "None", "Tree splits are scale-invariant"),
    ("K-Means scaling", "StandardScaler on full X", "Euclidean distance requires comparable scales"),
    ("Train-test split", "80/20 stratified", "702 train / 176 test; seed 42"),
]

TECHNIQUES_GLOSSARY = [
    ("Random Forest", "Supervised ensemble of decision trees with bootstrap aggregation and random feature subsets.",
     "Primary classifier for 1-year survival.", "class_weight=balanced; GridSearchCV; 300 trees, depth 15."),
    ("K-Means", "Unsupervised partitioning minimizing within-cluster sum of squared distances.",
     "Patient subgroup discovery.", "k=3; StandardScaler features; n_init=10; seed 42."),
    ("Logistic Regression", "Linear probabilistic classifier with log-odds link.",
     "Benchmark in Section 7.5.", "class_weight=balanced; scaled features."),
    ("SVM (RBF kernel)", "Maximum-margin classifier in kernel-transformed space.",
     "Benchmark; best macro F1 in comparison.", "class_weight=balanced; probability=True."),
    ("Gradient Boosting", "Sequential ensemble of shallow trees correcting prior errors.",
     "Benchmark with native feature importance.", "200 estimators; max_depth=3."),
    ("GMM / Ward / DBSCAN", "Alternative clustering: probabilistic, hierarchical, density-based.",
     "Unsupervised benchmarks in Section 6.", "Compared at k=2,3,4; DBSCAN eps/ms grid."),
    ("StandardScaler", "Z-score normalization: mean 0, variance 1 per feature.",
     "K-Means input only.", "Fit on full 878×20 matrix (unsupervised)."),
    ("PCA", "Orthogonal linear projection capturing maximum variance.",
     "2D visualization of clusters.", "PC1 20.3% + PC2 10.5% = 30.8% cumulative."),
    ("GridSearchCV", "Exhaustive hyperparameter search with cross-validation.",
     "Tune Random Forest.", "108 combinations; 5-fold stratified; scoring=f1 (binary)."),
    ("Cramér's V", "Effect size for categorical association (0 = none, 1 = perfect).",
     "Cluster vs survival after chi-square.", "V ≈ 0.048 — negligible."),
    ("VIF", "Variance inflation factor for multicollinearity.",
     "Section 4.6 audit.", "Elevated on NLR, PLR, SII, CRP/ALB; none dropped."),
]


def section_processes():
    return {
        "1": {
            "title": "SECTION 1: Project Setup and Imports",
            "overview": (
                "Established the computational environment, reproducibility controls, and plotting "
                "standards before any data were loaded."
            ),
            "simple": (
                "We set up the software toolbox and fixed random seeds so every chart and model "
                "result can be recreated exactly the same way later."
            ),
            "processes": [
                ("1.1", "Library imports", "Python scientific stack",
                 "Imported pandas, numpy, matplotlib, seaborn, scikit-learn (RF, KMeans, PCA, "
                 "StandardScaler, train_test_split, GridSearchCV, StratifiedKFold, metrics, "
                 "silhouette_score), scipy (chi2, normaltest), statsmodels (VIF). SMOTE imported "
                 "but not applied.",
                 "N/A", "All dependencies loaded; warnings suppressed.",
                 "SMOTE documented as rejected alternative.",
                 "We loaded programs for tables, graphs, and machine learning."),
                ("1.2", "Reproducibility", "Fixed random seed",
                 "RANDOM_STATE=42 on split, KMeans, RF, StratifiedKFold, PCA. OPTIMAL_K=3 documented.",
                 "random_state=42", "Identical splits and fits on re-run.",
                 "Mandatory for academic reproducibility.",
                 "We fixed the randomness so results do not change every run."),
                ("1.3", "Visualization defaults", "matplotlib + seaborn",
                 "Style seaborn-v0_8-whitegrid; colorblind palette; figsize defaults; savefig dpi=300, "
                 "bbox_inches='tight'; figures/ directory created.",
                 "dpi=300", "Publication-quality exports.",
                 "Consistent visuals for report and defense.",
                 "We chose clear, high-resolution saved images."),
            ],
        },
        "2": {
            "title": "SECTION 2: Data Loading and Initial Inspection",
            "overview": "Loaded Excel data, audited structure, removed unusable columns, renamed target.",
            "simple": "We opened the patient spreadsheet, checked it, and prepared a clean table for analysis.",
            "processes": [
                ("2.1", "Load Excel", "pd.read_excel",
                 "Read PCSPF workbook. Verified shape (878, 24).",
                 "openpyxl", "DataFrame 878×24.",
                 "Single authoritative source file.",
                 "We imported 878 patient rows from Excel."),
                ("2.2", "Structural inspection", "Descriptive audit",
                 "Columns, dtypes, head/tail, null counts, duplicates.",
                 "N/A", "878 nulls each in Predict label columns; 0 duplicates.",
                 "Predict columns unusable; ID all 'xxx'.",
                 "We listed columns, types, and missing values."),
                ("2.3", "Target distribution", "value_counts",
                 "Class 1: 604 (68.8%); Class 0: 274 (31.2%); ratio 2.20:1.",
                 "N/A", "Majority baseline = 68.8% accuracy.",
                 "Drives class_weight and metric choice.",
                 "About 7 in 10 patients survived at least one year."),
                ("2.4", "Column removal", "drop + rename",
                 "Dropped ID, Predict label 1, Predict label 0. Renamed target to survival_label.",
                 "DROP_COLS", "Clean shape (878, 21) = 20 features + target.",
                 "Asserted expected dimensions.",
                 "We removed useless columns and renamed the outcome."),
                ("2.5", "Pre-standardized note (audit)", "Descriptive check",
                 "Verified continuous features have mean≈0, std≈1 in released file.",
                 "N/A", "Markdown + code audit cell.",
                 "Explains EDA scale; scaling still applied for K-Means.",
                 "We noted the file already used z-scores for lab columns."),
            ],
        },
        "3": {
            "title": "SECTION 3: Exploratory Data Analysis (EDA)",
            "overview": "Characterized distributions, class balance, correlations, and survival-group differences.",
            "simple": "We explored the data with charts and tables before building models.",
            "processes": [
                ("3.1", "Summary statistics", "describe()",
                 "Count, mean, std, min, quartiles, max for all 20 features.",
                 "Transposed table", "Displayed in notebook.",
                 "Confirmed z-score scale in released data.",
                 "We calculated average and spread of each measurement."),
                ("3.2", "Target bar chart", "matplotlib bar",
                 "Class counts with percent labels → target_distribution.png.",
                 "dpi=300", "Imbalance ratio 2.20:1 printed.",
                 "Foreshadows class_weight strategy.",
                 "We charted survivors vs non-survivors."),
                ("3.3", "Feature histograms", "histplot + KDE",
                 "4×5 grid for 18 continuous features → feature_distributions.png.",
                 "30 bins", "Right-skew on CEA, CRP, NLR, bilirubin.",
                 "Informs normality testing in Section 4.",
                 "We drew distribution shapes for each lab."),
                ("3.4", "Survival boxplots", "boxplot by class",
                 "Grouped by survival_label → boxplots_by_survival.png.",
                 "colorblind palette", "Modest separation on CA19-9, inflammation.",
                 "Weak univariate signal motivates multivariate models.",
                 "We compared labs between outcome groups."),
                ("3.5", "Correlation heatmap", "seaborn heatmap",
                 "Pearson matrix, upper triangle masked → correlation_heatmap.png.",
                 "Annotated r values", "All |r| with target < 0.15.",
                 "Strong inter-feature collinearity among ratios.",
                 "We mapped which variables move together."),
                ("3.6", "Multicollinearity narrative", "Markdown",
                 "Documented NLR, PLR, SII, CRP/ALB formulas.",
                 "N/A", "Conceptual link to VIF in Section 4.",
                 "Prepares defense on retaining correlated features.",
                 "We explained why some columns overlap clinically."),
                ("3.7", "Class-conditional means", "groupby + bar chart",
                 "Mean diff class 0 vs 1; top 10 → class_conditional_means.png.",
                 "Sorted by |diff|", "Largest gaps: Abdominal Pain, CA19-9, Prealbumin.",
                 "Quantifies weak univariate separation.",
                 "We measured which labs differ most by outcome."),
                ("3.8", "EDA summary", "Synthesis markdown",
                 "Four themes: distributions, correlations, class gaps, modeling implications.",
                 "N/A", "Bridges EDA to preprocessing.",
                 "Single narrative checkpoint.",
                 "We summarized findings before modeling."),
            ],
        },
        "4": {
            "title": "SECTION 4: Data Preprocessing",
            "overview": "Documented every data decision including deliberate non-actions, with clinical justification.",
            "simple": "We recorded every preparation choice—and what we chose NOT to do and why.",
            "processes": [
                ("4.1", "Data types", "dtype audit", "All numeric; binary cols {0,1}.", "N/A", "No casting needed.", "Confirmed in markdown.", "We checked column types."),
                ("4.2", "Missing values", "isnull audit", "Triple check — all zero.", "N/A", "No imputation.", "Three verification methods.", "We confirmed no empty cells."),
                ("4.3", "Duplicates", "duplicated()", "0 exact duplicates.", "N/A", "All rows retained.", "Documented.", "No duplicate patients."),
                ("4.4", "Outliers", "IQR 1.5× rule",
                 "Counts per feature; z-score boxplot → outlier_boxplots.png.",
                 "1.5×IQR", "Decision: RETAIN all outliers.",
                 "Clinical extremes are informative.",
                 "We counted extremes but kept them."),
                ("4.5", "Skewness & normality", "normaltest",
                 "Skew/kurtosis table; D'Agostino-Pearson per feature.",
                 "alpha=0.05", "Most non-normal; no transform applied.",
                 "RF uses ranks; K-Means uses scaler.",
                 "We tested bell-curve assumptions."),
                ("4.6", "VIF", "variance_inflation_factor",
                 "VIF for all 20 features; sorted interpretation table.",
                 "statsmodels", "High VIF on ratio features.",
                 "Decision: RETAIN all features.",
                 "We measured overlap but kept clinical indices."),
                ("4.7", "Feature engineering", "None",
                 "Existing ratios sufficient; no binning or interactions.",
                 "N/A", "Markdown only.", "Avoid arbitrary information loss.", "No new columns created."),
                ("4.8", "Feature selection", "Retain all 20",
                 "Same set for RF and K-Means; importance post-hoc.",
                 "N/A", "Consistent pipelines.", "Same inputs both analyses.", "All 20 features used."),
                ("4.9", "Class imbalance", "class_weight",
                 "Documented weights; rejected SMOTE.",
                 "balanced", "F1, AUC primary metrics.", "Real patients only.", "Model weights minority class more."),
                ("4.10", "Summary table", "matplotlib table",
                 "11-row decision register → preprocessing_summary.png.",
                 "N/A", "Master audit reference.", "Single consolidated table.", "One table of all prep choices."),
            ],
        },
        "5": {
            "title": "SECTION 5: Train-Test Split and Scaling",
            "overview": "Separated X and y, stratified 80/20 split, scaling for K-Means only.",
            "simple": "We divided data for fair testing and scaled only for grouping.",
            "processes": [
                ("5.1", "Feature-target split", "X, y", "X: 878×20; y: survival_label.", "N/A", "Shapes printed.", "Supervised foundation.", "Separated inputs from outcome."),
                ("5.2", "Train-test split", "train_test_split",
                 "80/20 stratified → 702 train, 176 test.", "seed=42", "Class proportions preserved.", "Holdout for RF.", "20% hidden for final test."),
                ("5.3", "StandardScaler", "fit on full X",
                 "Before/after stats; boxplot → scaling_before_after.png.",
                 "StandardScaler()", "X_scaled for K-Means.", "RF uses unscaled train/test.", "Scaled labs for fair clustering distances."),
            ],
        },
        "6": {
            "title": "SECTION 6: Unsupervised Learning — K-Means Clustering",
            "overview": (
                "Method comparison (K-Means, GMM, Ward, DBSCAN), model selection, clustering, "
                "profiling, and survival overlay without using target during fit."
            ),
            "simple": "We compared grouping methods, chose K-Means, found three patient types, then checked survival.",
            "processes": [
                ("6.0", "Method comparison (audit)", "Multi-algorithm benchmark",
                 "K-Means, GMM, Ward (k=2–4); DBSCAN (3 configs). Metrics: silhouette, chi-sq p, "
                 "Cramér's V, survival spread, smallest cluster, assignment %.",
                 "Same X_scaled, seed 42", "unsupervised_model_comparison.png.",
                 "K-Means selected: best silhouette at k=3, 100% assignment, centroids.",
                 "We compared four grouping methods before choosing K-Means."),
                ("6.1", "Elbow method", "KMeans inertia",
                 "k=2..10 on X_scaled → elbow_method.png.", "n_init=10", "Elbow region k=2–4.", "Supports k choice.", "Found where extra groups help less."),
                ("6.2", "Silhouette analysis", "silhouette_score",
                 "Mean silhouette per k → silhouette_scores.png.", "k=2..10", "Max at k=2 (~0.206).", "Compared with elbow.", "Scored cluster tightness."),
                ("6.3", "Choose k=3", "Structured justification",
                 "k=3 for three clinical phenotypes despite k=2 silhouette peak.", "OPTIMAL_K=3", "Documented trade-off.", "Clinical interpretability.", "We picked three patient types."),
                ("6.4", "Final K-Means", "fit_predict",
                 "Labels for 878 patients; cluster sizes printed.", "seed=42", "df['cluster'] assigned.", "Target not used in fit.", "Every patient got a group."),
                ("6.5", "PCA visualization", "PCA n=2",
                 "Variance ratios; scatter → pca_clusters.png.", "PCA", "PC1+PC2 = 30.8%.", "PCA variance caveat added (audit).", "2D picture of groups."),
                ("6.6", "Cluster profiling", "groupby + heatmap",
                 "Mean/std tables; z-scored heatmap → cluster_profiles_heatmap.png.", "N/A", "Three clinical phenotypes.", "Low/mid/high inflammation profiles.", "Described each group medically."),
                ("6.7", "Survival overlay", "chi-square + Cramér's V",
                 "Crosstab; survival %; bar chart; chi2 p=0.2546; V≈0.048.",
                 "chi-square", "cluster_survival_overlay.png.", "Not significant; negligible effect.", "Groups don't strongly predict survival."),
                ("6.8", "PCA by survival", "scatter by label",
                 "Same PCA colored by true survival → pca_survival_labels.png.", "N/A", "Partial alignment with clusters.", "Bridge to supervised outcome.", "Overlaid survival on 2D map."),
            ],
        },
        "7": {
            "title": "SECTION 7: Supervised Learning — Random Forest Classifier",
            "overview": (
                "RF justification, baseline, GridSearchCV, full evaluation with overfitting audit, "
                "regularization comparison, and multi-model benchmark."
            ),
            "simple": "We explained why RF, tuned it, measured overfitting, and compared to other classifiers.",
            "processes": [
                ("7.0", "Why Random Forest? (audit)", "Five-factor markdown",
                 "Non-linear interactions, Gini importance, multicollinearity robustness, no scaling, course scope.",
                 "N/A", "Pre-7.1 justification.", "Aligns with synthesis requirements.", "We wrote why RF fits this project."),
                ("7.1", "Baseline RF", "RandomForestClassifier",
                 "100 trees, balanced; fit X_train.", "n_estimators=100", "Acc 68.18% on test.", "Benchmark before tuning.", "First draft model."),
                ("7.2", "GridSearchCV", "Hyperparameter search",
                 "108 combos; 5-fold stratified CV; scoring=f1 (binary).",
                 "Best: 300 trees, depth 15", "CV F1 ~0.809 (binary).", "CV vs test F1 clarified (audit).", "Auto-picked best settings."),
                ("7.3", "Test evaluation", "Full metric suite",
                 "Accuracy 71.02%; macro F1 0.507; AUC 0.613; CM; ROC; classification report figures.",
                 "176-patient holdout", "4 figures saved.", "Train 100% vs test 71% gap documented.", "Scored on unseen patients."),
                ("7.3a", "Overfitting assessment (audit)", "Train vs test table",
                 "100% train accuracy; 29 pp gap; AUC train vs test compared.", "N/A", "Markdown interpretation.", "Memorization documented.", "Model memorized training data."),
                ("7.3b", "Regularization comparison (audit)", "Constrained RF configs",
                 "Shallower trees / larger leaves reduce gap at accuracy cost.", "N/A", "Trade-off table.", "No config reaches AUC 0.7.", "Stricter trees generalize better but score lower."),
                ("7.3c", "Class-0 recall (audit)", "Confusion matrix narrative",
                 "Low recall for shorter-survival class despite balanced weights.", "N/A", "Clinical limitation stated.", "Many high-risk patients missed.", "Model under-detects worst outcomes."),
                ("7.4", "Feature importance", "Gini importances",
                 "Bar chart all 20 features → feature_importance.png.", "Gini", "Top: CEA, Prealbumin, CA19-9.", "Feeds Section 8 synthesis.", "Ranked which labs matter most."),
                ("7.5", "Model comparison (audit)", "RF vs LR vs SVM vs GB",
                 "Same split/seed; train acc, test acc, overfit gap, macro F1, AUC, CV macro F1.",
                 "Pipeline CV for scaled models", "supervised_model_comparison.png.", "All AUC < 0.63; RF kept for importance.", "Compared four prediction methods."),
            ],
        },
        "8": {
            "title": "SECTION 8: Synthesis and Bridging Analysis",
            "overview": "Connected RF importances, cluster structure, predicted probabilities, limitations, future work.",
            "simple": "We compared predictions with groups to see if both analyses agree.",
            "processes": [
                ("8.1", "Importance vs differentiation", "Rank comparison",
                 "RF rank vs cluster mean-range rank → synthesis_comparison.png.", "N/A", "Convergence in top features.", "Mutual validation.", "Checked if predictors define groups."),
                ("8.2", "Probability by cluster", "predict_proba",
                 "Mean predicted vs actual survival rate per cluster.", "tuned RF on full X", "Bridge table.", "Calibration across subgroups.", "Compared model confidence per group."),
                ("8.3", "Clinical synthesis", "Dynamic narrative",
                 "High-risk cluster 2 vs low-risk cluster 0; convergence paragraph.", "runtime vars", "Rendered markdown.", "Medical story.", "Wrote connected clinical interpretation."),
                ("8.4", "Limitations", "10 items",
                 "Imbalance, weak signal, overfitting, no external validation, K-Means assumptions, etc.",
                 "N/A", "Numbered list.", "Honest scope.", "Listed what study cannot claim."),
                ("8.5", "Future work", "10 items",
                 "XGBoost, SHAP, Cox models, GMM/DBSCAN validation, external cohorts, staging features.",
                 "N/A", "Research directions.", "Beyond course scope.", "Listed next research steps."),
            ],
        },
        "9": {
            "title": "SECTION 9: Conclusion",
            "overview": "Four-paragraph recap with metrics from runtime variables.",
            "simple": "The ending auto-fills real numbers from the executed notebook.",
            "processes": [
                ("9.1", "Dynamic conclusion", "Markdown f-string",
                 "Objective, supervised results, unsupervised results, bridging insight.",
                 "tuned_acc, auc, macro_f1, clusters, chi2 p", "KEY RESULTS block + rendered text.",
                 "Avoids stale hard-coded metrics.", "Summary always matches latest run."),
            ],
        },
    }
