# -*- coding: utf-8 -*-
"""Structured content for the capstone audit PDF."""

PROJECT = {
    "title": "PCSPF Pancreatic Cancer Survival — Complete Project Documentation",
    "subtitle": "Technical Process Record, Methodology Audit, and Plain-Language Companion",
    "course": "Fundamentals of Data Science — CMSC 176",
    "institution": "University of the Philippines Manila",
    "notebook": "PCSPF_Data_Science_Capstone.ipynb",
    "data_file": "Dataset/PCSPF-Pancreatic Cancer Survival based on Preoperative Features.xlsx",
    "n_patients": 878,
    "n_features": 20,
    "random_state": 42,
    "optimal_k": 3,
}

RESULTS = {
    "baseline_acc": "68.8%",
    "untuned_acc": "68.18%",
    "tuned_acc": "71.02%",
    "improvement_pp": "+2.27",
    "auc": "0.613",
    "macro_f1": "0.507",
    "cv_f1": "~0.809",
    "chi2_p": "0.2546",
    "top_features": ["CEA", "Prealbumin", "CA19-9", "Total Bilirubin", "BMI"],
    "best_rf_params": {
        "n_estimators": 300,
        "max_depth": 15,
        "min_samples_split": 2,
        "min_samples_leaf": 1,
    },
    "clusters": [
        ("0", "519", "59%", "70.1%", "Lower inflammation; higher prealbumin/ALB"),
        ("1", "204", "23%", "69.6%", "Elevated bilirubin, NLR, SII; lower prealbumin"),
        ("2", "155", "18%", "63.2%", "Highest CRP/CRP/ALB; more abdominal pain"),
    ],
}

FIGURES = [
    ("1", "target_distribution.png", "3.2", "Bar chart of class 0 vs class 1 with count and percent labels"),
    ("2", "feature_distributions.png", "3.3", "4x5 grid of histograms + KDE for 18 continuous features"),
    ("3", "boxplots_by_survival.png", "3.4", "Boxplots of each continuous feature by survival label"),
    ("4", "correlation_heatmap.png", "3.5", "Lower-triangle Pearson correlation heatmap (20 features + target)"),
    ("5", "class_conditional_means.png", "3.7", "Horizontal bar chart of top 10 mean differences by class"),
    ("6", "outlier_boxplots.png", "4.4", "Per-feature z-score boxplots for outlier comparison"),
    ("7", "preprocessing_summary.png", "4.10", "Table figure of all preprocessing decisions"),
    ("8", "scaling_before_after.png", "5.3", "Side-by-side boxplots before/after StandardScaler"),
    ("9", "elbow_method.png", "6.1", "Line plot of inertia vs k (2-10) with elbow marker"),
    ("10", "silhouette_scores.png", "6.2", "Line plot of mean silhouette vs k"),
    ("11", "pca_clusters.png", "6.5", "2D PCA scatter colored by cluster + centroids"),
    ("12", "cluster_profiles_heatmap.png", "6.6", "Heatmap of z-scored mean features per cluster"),
    ("13", "cluster_survival_overlay.png", "6.7", "Grouped bar chart of survival counts per cluster"),
    ("14", "pca_survival_labels.png", "6.8", "2D PCA scatter colored by true survival"),
    ("15", "confusion_matrix.png", "7.3", "Seaborn heatmap of tuned RF predictions"),
    ("16", "roc_curve.png", "7.3", "ROC with AUC annotation and diagonal reference"),
    ("17", "feature_importance.png", "7.4", "Horizontal bar chart of all 20 Gini importances"),
    ("18", "classification_report.png", "7.3", "Tabular precision/recall/F1 figure"),
    ("19", "synthesis_comparison.png", "8.1", "Side-by-side top-10 RF vs cluster-differentiation"),
]

# Each process: id, name, technique, what_we_did, parameters, output, decision, simple
def section_processes():
    return {
        "1": {
            "title": "SECTION 1: Project Setup and Imports",
            "overview": (
                "Established the computational environment, reproducibility controls, and plotting "
                "standards before any data were loaded."
            ),
            "simple": (
                "We set up the software toolbox and rules so every chart and model result can be "
                "recreated exactly the same way later."
            ),
            "processes": [
                ("1.1", "Library imports", "Python scientific stack",
                 "Imported pandas and numpy for data; matplotlib and seaborn for visuals; scikit-learn "
                 "for RandomForestClassifier, KMeans, PCA, StandardScaler, train_test_split, GridSearchCV, "
                 "StratifiedKFold, classification metrics, silhouette_score; imbalanced-learn SMOTE (documented, "
                 "not used); scipy chi2_contingency, shapiro, normaltest; statsmodels variance_inflation_factor.",
                 "N/A", "All dependencies loaded; warnings suppressed for clean output.",
                 "SMOTE imported only to document alternative imbalance strategy.",
                 "We loaded programs for tables, graphs, and machine learning."),
                ("1.2", "Reproducibility", "Fixed random seed",
                 "Set RANDOM_STATE = 42 on numpy, train_test_split, KMeans, RandomForest, StratifiedKFold, PCA. "
                 "Set OPTIMAL_K = 3 as documented cluster choice.",
                 "random_state=42 everywhere", "Identical splits and model fits on re-run.",
                 "Mandatory for academic reproducibility.",
                 "We fixed the 'randomness dice' so results do not change every time."),
                ("1.3", "Visualization defaults", "matplotlib + seaborn",
                 "Style: seaborn-v0_8-whitegrid; palette colorblind; figure 10x6; savefig dpi=300; font sizes 10-13pt.",
                 "dpi=300 for saved figures", "figures/ directory created with os.makedirs.",
                 "Publication-quality exports required by capstone spec.",
                 "We chose consistent colors and large, clear saved images for the report."),
            ],
        },
        "2": {
            "title": "SECTION 2: Data Loading and Initial Inspection",
            "overview": "Loaded raw Excel data, audited structure and quality, removed unusable columns, renamed target.",
            "simple": "We opened the patient spreadsheet, checked it, and prepared a clean table for analysis.",
            "processes": [
                ("2.1", "Load Excel", "pd.read_excel",
                 "Read PCSPF workbook into df_raw. Verified shape (878, 24).",
                 "engine: openpyxl", "DataFrame 878 rows x 24 columns.",
                 "Single source file; no external augmentation.",
                 "We imported 878 patient rows from Excel."),
                ("2.2", "Structural inspection", "Descriptive audit",
                 "Displayed column names, dtypes, head(5), tail(5), isnull().sum(), duplicated().sum().",
                 "N/A", "Confirmed 878 nulls each in Predict label 1 and 0; 0 duplicates.",
                 "Predict columns unusable; ID all 'xxx'.",
                 "We listed columns, types, and missing values."),
                ("2.3", "Target distribution", "value_counts",
                 "Class 1: 604 (68.8%); Class 0: 274 (31.2%); ratio 2.20:1.",
                 "N/A", "Imbalance documented for later class_weight.",
                 "Majority baseline accuracy = 68.8%.",
                 "About 7 in 10 patients survived at least one year in this dataset."),
                ("2.4", "Column removal", "drop + rename",
                 "Dropped ID, Predict label 1, Predict label 0. Renamed long label column to survival_label.",
                 "DROP_COLS list", "Clean shape (878, 21) = 20 features + target.",
                 "Asserted shape equals expected dimensions.",
                 "We removed useless columns and gave the outcome a short name."),
            ],
        },
        "3": {
            "title": "SECTION 3: Exploratory Data Analysis (EDA)",
            "overview": "Characterized distributions, class balance, correlations, and survival-group differences before modeling.",
            "simple": "We explored the data with charts and tables to understand patterns before building models.",
            "processes": [
                ("3.1", "Summary statistics", "DataFrame.describe()",
                 "Computed count, mean, std, min, quartiles, max for all 20 features.",
                 "Transposed for readability", "Table displayed in notebook.",
                 "Noted z-score scale (mean~0, std~1) in released file.",
                 "We calculated average, spread, and range of each measurement."),
                ("3.2", "Target bar chart", "matplotlib bar + annotations",
                 "Plotted class counts; labeled percents; saved target_distribution.png.",
                 "dpi=300", "Figure + printed imbalance ratio 2.20:1.",
                 "Foreshadowed class_weight strategy.",
                 "We charted how many survived vs did not."),
                ("3.3", "Feature histograms", "seaborn histplot + KDE",
                 "4x5 grid for 18 continuous features; saved feature_distributions.png.",
                 "30 bins", "Identified right-skewed markers (CEA, CRP, NLR, etc.).",
                 "Visual normality assessment before formal tests.",
                 "We drew distribution shapes for each lab test."),
                ("3.4", "Survival boxplots", "seaborn boxplot by class",
                 "Grouped boxplots per feature by survival_label; saved boxplots_by_survival.png.",
                 "colorblind palette", "Modest separation on CA19-9, inflammation markers.",
                 "Weak overlap motivates multivariate models.",
                 "We compared lab values between survivors and non-survivors."),
                ("3.5", "Correlation heatmap", "seaborn heatmap, mask upper triangle",
                 "Full Pearson matrix; annotated r values; saved correlation_heatmap.png.",
                 "coolwarm/RdBu_r", "Max |r| with target < 0.15.",
                 "Strong inter-feature collinearity among ratios documented.",
                 "We mapped which variables move together."),
                ("3.6", "Multicollinearity narrative", "Markdown analysis",
                 "Documented NLR, PLR, SII, CRP/ALB formulas and bilirubin physiology.",
                 "N/A", "Implications stated for RF vs K-Means.",
                 "No code; conceptual section.",
                 "We explained why some columns repeat similar information."),
                ("3.7", "Class-conditional means", "groupby mean, diff table, bar chart",
                 "Compared mean per feature class 0 vs 1; sorted by abs difference; saved class_conditional_means.png.",
                 "Top 10 features plotted", "Largest gaps: Abdominal Pain, CA19-9, Prealbumin.",
                 "Quantified weak univariate separation.",
                 "We measured which labs differ most between outcome groups."),
                ("3.8", "EDA summary", "Synthesis markdown",
                 "Four themes: distributions, correlations, class differences, modeling implications.",
                 "N/A", "Informed preprocessing and model choice.",
                 "Single summary ties EDA to next sections.",
                 "We wrote what we learned before cleaning and modeling."),
            ],
        },
        "4": {
            "title": "SECTION 4: Data Preprocessing",
            "overview": "Documented every data decision including deliberate non-actions, with clinical and statistical justification.",
            "simple": "We recorded every cleaning and preparation choice—and what we chose NOT to do and why.",
            "processes": [
                ("4.1", "Data types", "dtype audit",
                 "Verified Sex and Abdominal Pain binary int; 18 continuous float64; no casting needed.",
                 "unique() on binary cols", "All numeric and valid.",
                 "Stated in markdown confirmation cell.",
                 "We checked each column was the right number type."),
                ("4.2", "Missing values", "isnull triple check",
                 "Per-column sum, total sum, isna().any().any() — all zero on cleaned data.",
                 "N/A", "No imputation required.",
                 "Three independent verification methods.",
                 "We confirmed no empty cells in usable columns."),
                ("4.3", "Duplicates", "duplicated().sum()",
                 "Found 0 exact duplicate rows; none removed.",
                 "N/A", "Each row treated as unique patient.",
                 "Documented in markdown.",
                 "We checked no patient row was copied twice."),
                ("4.4", "Outliers", "IQR rule 1.5x",
                 "Per continuous feature: Q1, Q3, IQR, bounds, outlier counts and %; z-score boxplot figure.",
                 "1.5 * IQR", "outlier_boxplots.png; table displayed.",
                 "Decision: RETAIN all outliers (clinical + RF robust + sample size).",
                 "We counted extreme lab values but kept them because they matter medically."),
                ("4.5", "Skewness & normality", "skew, kurtosis, normaltest",
                 "Skewness table with interpretation bands; D'Agostino-Pearson per feature with Normal? flag.",
                 "alpha=0.05", "Most features non-normal; shapiro imported not run.",
                 "Decision: NO log/Box-Cox/Yeo-Johnson.",
                 "We tested bell-curve assumptions and decided transforms were not needed."),
                ("4.6", "VIF", "variance_inflation_factor",
                 "VIF for all 20 features; sorted table with low/moderate/high interpretation.",
                 "statsmodels VIF", "Elevated VIF on ratio features and components.",
                 "Decision: RETAIN all features.",
                 "We measured overlap between columns but kept all for clinical reasons."),
                ("4.7", "Feature engineering", "None added",
                 "Existing NLR, PLR, SII, CRP/ALB sufficient; rejected binning and interaction terms.",
                 "N/A", "Markdown justification only.",
                 "Avoid arbitrary information loss.",
                 "We did not create new calculated columns."),
                ("4.8", "Feature selection", "Retain all 20",
                 "RF: use importance post-hoc; K-Means: all features with collinearity caveat.",
                 "N/A", "Consistent feature set across pipelines.",
                 "Same inputs for supervised and unsupervised.",
                 "We used all 20 measurements in both models."),
                ("4.9", "Class imbalance", "class_weight strategy",
                 "Documented weights ~1.60 class 0, ~0.73 class 1; rejected SMOTE.",
                 "balanced", "F1 and AUC as primary metrics.",
                 "Preserves real patients vs synthetic.",
                 "We told the model to pay more attention to the smaller group."),
                ("4.10", "Preprocessing summary", "Table + figure",
                 "11-row decision table rendered to preprocessing_summary.png.",
                 "matplotlib table", "Single reference for entire Section 4.",
                 "Consolidates audit trail.",
                 "We made one master table of all preparation decisions."),
            ],
        },
        "5": {
            "title": "SECTION 5: Train-Test Split and Scaling",
            "overview": "Separated X and y, stratified 80/20 split, applied scaling only for K-Means pipeline.",
            "simple": "We divided data for fair testing and scaled numbers only for the grouping method.",
            "processes": [
                ("5.1", "Feature-target split", "X, y DataFrames",
                 "X: 878x20 features; y: survival_label.",
                 "N/A", "Shapes printed.",
                 "Foundation for supervised pipeline.",
                 "We separated inputs from the outcome column."),
                ("5.2", "Train-test split", "train_test_split stratified",
                 "test_size=0.2, stratify=y, random_state=42 → train 702, test 176.",
                 "80/20", "Class proportions preserved in both sets.",
                 "20% holdout for unbiased RF evaluation.",
                 "We hid 20% of patients to test predictions later."),
                ("5.3", "StandardScaler", "fit on full X for K-Means",
                 "Before/after min, max, mean, std table; side-by-side boxplot figure.",
                 "StandardScaler()", "scaling_before_after.png.",
                 "RF explicitly NOT scaled.",
                 "We put all lab tests on the same scale for fair distance grouping."),
            ],
        },
        "6": {
            "title": "SECTION 6: Unsupervised Learning — K-Means",
            "overview": "Clustered patients on scaled features without survival_label; evaluated k; profiled clusters; bridged to outcomes.",
            "simple": "We grouped similar patients by lab tests alone, then checked if those groups differed in survival.",
            "processes": [
                ("6.1", "Elbow method", "KMeans inertia loop",
                 "Fit k=2..10 on X_scaled; plot inertia vs k; elbow heuristic line.",
                 "n_init=10", "elbow_method.png.",
                 "Identifies diminishing returns in cluster count.",
                 "We found where adding groups stops helping much."),
                ("6.2", "Silhouette analysis", "silhouette_score loop",
                 "Mean silhouette per k; plot; max at k=2 (score ~0.206).",
                 "k=2..10", "silhouette_scores.png.",
                 "Compared with elbow for k choice.",
                 "We scored how tight and separated groups are."),
                ("6.3", "Choose k=3", "Structured justification",
                 "Silhouette favors k=2; chose k=3 for three clinical phenotypes and interpretability.",
                 "OPTIMAL_K=3", "Documented in markdown.",
                 "Trade-off statistical vs clinical granularity.",
                 "We picked three patient types, not two."),
                ("6.4", "Final K-Means", "fit_predict",
                 "Labels for 878 patients; cluster size counts printed.",
                 "random_state=42, n_init=10", "df['cluster'] assigned.",
                 "Target never used in fit.",
                 "We assigned every patient to a group."),
                ("6.5", "PCA visualization", "PCA n_components=2",
                 "Explained variance printed; scatter by cluster; centroids marked.",
                 "PCA", "pca_clusters.png.",
                 "2D view of 20-D structure.",
                 "We drew a 2D picture of the groups."),
                ("6.6", "Cluster profiling", "groupby mean/std, heatmap",
                 "Mean and std tables; z-scored heatmap of cluster profiles.",
                 "N/A", "cluster_profiles_heatmap.png.",
                 "Clinical interpretation of three phenotypes.",
                 "We described what each group looks like medically."),
                ("6.7", "Survival overlay", "crosstab + chi-square",
                 "Counts table; survival % per cluster; bar chart; chi2_contingency with expected freqs.",
                 "chi-square", "cluster_survival_overlay.png; p=0.2546.",
                 "Association not significant at 0.05.",
                 "We tested if groups differ in who survived."),
                ("6.8", "PCA by survival", "Same PCA, color by label",
                 "Compare cluster vs survival coloring in 2D.",
                 "N/A", "pca_survival_labels.png.",
                 "Bridge unsupervised to supervised outcome.",
                 "We overlaid true survival on the same 2D map."),
            ],
        },
        "7": {
            "title": "SECTION 7: Supervised Learning — Random Forest",
            "overview": "Binary classification of 1-year survival with balanced Random Forest, grid search, and full evaluation.",
            "simple": "We built a prediction tool for survival and measured how well it works.",
            "processes": [
                ("7.1", "Baseline RF", "RandomForestClassifier",
                 "100 trees, class_weight balanced; fit X_train; evaluate X_test.",
                 "n_estimators=100", "Baseline acc 68.18%; CM and report printed.",
                 "Benchmark before tuning.",
                 "We ran a first draft model for comparison."),
                ("7.2", "GridSearchCV", "Hyperparameter search",
                 "Grid: n_estimators [100,200,300], max_depth [None,10,15,20], min_samples_split [2,5,10], "
                 "min_samples_leaf [1,2,4]; 108 combos; 5-fold stratified CV; scoring=f1.",
                 "StratifiedKFold(5)", "Best: 300 trees, depth 15; CV F1 ~0.809.",
                 "Top 10 combos table displayed.",
                 "We automatically tried many settings and picked the best."),
                ("7.3", "Test evaluation", "Metrics suite",
                 "Accuracy vs baselines; classification report figure; confusion matrix; ROC AUC 0.613; metrics table.",
                 "holdout 176 patients", "4 figures saved.",
                 "Discussed FN vs FP clinically.",
                 "We scored final performance on unseen patients."),
                ("7.4", "Feature importance", "feature_importances_",
                 "Horizontal bar chart all 20 features; top 5 and bottom 5 printed.",
                 "Gini importance", "feature_importance.png.",
                 "CEA, Prealbumin, CA19-9 lead.",
                 "We ranked which labs mattered most for predictions."),
            ],
        },
        "8": {
            "title": "SECTION 8: Synthesis and Bridging Analysis",
            "overview": "Connected supervised importances, unsupervised structure, and predicted probabilities.",
            "simple": "We compared prediction results with patient groups to see if both analyses tell the same story.",
            "processes": [
                ("8.1", "Importance vs differentiation", "Rank comparison",
                 "RF importance rank vs cluster mean-range rank; side-by-side chart.",
                 "N/A", "synthesis_comparison.png.",
                 "Overlap in top features = convergence.",
                 "We checked if important predictors also define groups."),
                ("8.2", "Probability by cluster", "predict_proba on full X",
                 "Mean predicted survival probability vs actual rate per cluster.",
                 "tuned RF", "Bridge table with difference column.",
                 "Calibration across subgroups.",
                 "We compared model confidence in each group."),
                ("8.3", "Clinical synthesis", "Dynamic narrative",
                 "High-risk cluster 2 vs low-risk cluster 0; convergence paragraph.",
                 "runtime vars", "Rendered from executed results.",
                 "Mutual validation narrative.",
                 "We wrote the medical story connecting both analyses."),
                ("8.4", "Limitations", "10 items",
                 "Imbalance, weak correlations, no external validation, K-Means assumptions, etc.",
                 "N/A", "Numbered list.",
                 "Honest scope boundaries.",
                 "We listed what the study cannot claim."),
                ("8.5", "Future work", "10 items",
                 "XGBoost, DBSCAN, transforms, SHAP, Cox models, external validation, staging features, etc.",
                 "N/A", "Research directions listed in notebook markdown.",
                 "Not implemented in current scope.",
                 "We listed next steps for stronger research if the project continues."),
            ],
        },
        "9": {
            "title": "SECTION 9: Conclusion",
            "overview": "Four-paragraph recap with metrics injected from runtime variables.",
            "simple": "The ending pulls real numbers from the run so the summary always matches results.",
            "processes": [
                ("9.1", "Dynamic conclusion", "IPython.display.Markdown f-string",
                 "Paragraphs: objective, supervised results, unsupervised results, bridging insight.",
                 "tuned_acc, roc_auc, macro_f1, top_feats, surv_rate, p",
                 "KEY RESULTS print block + rendered markdown.",
                 "Avoids stale hard-coded metrics.",
                 "The final summary auto-fills accuracy, AUC, clusters, and p-value."),
            ],
        },
    }


TECHNIQUES_GLOSSARY = [
    ("Random Forest", "Supervised ensemble of decision trees; each tree votes; handles non-linear patterns.",
     "Predict 1-year survival from 20 labs.", "class_weight=balanced; tuned via GridSearchCV."),
    ("K-Means", "Unsupervised partitioning into k groups by minimizing within-cluster distance.",
     "Discover patient subgroups.", "Euclidean distance on StandardScaler features; k=3."),
    ("StandardScaler", "Transforms each feature to mean 0, variance 1.",
     "Fair distance for K-Means.", "Fit on full X (878 rows) — unsupervised only."),
    ("PCA", "Linear reduction to orthogonal components capturing variance.",
     "Visualize 20-D clusters in 2D.", "2 components; variance ratios reported."),
    ("GridSearchCV", "Exhaustive search over hyperparameter grid with cross-validation.",
     "Optimize RF settings.", "108 combinations; 5 stratified folds; F1 score."),
    ("StratifiedKFold", "CV folds preserve class proportions.",
     "Fair tuning under imbalance.", "5 splits, shuffle, random_state=42."),
    ("D'Agostino-Pearson", "Normality test using skewness and kurtosis.",
     "Test if features are bell-shaped.", "normaltest(); alpha 0.05."),
    ("IQR outlier rule", "Flag points outside Q1-1.5*IQR or Q3+1.5*IQR.",
     "Quantify extremes.", "Counted but not removed."),
    ("VIF", "Variance Inflation Factor; detects multicollinearity.",
     "Check redundant columns.", "All 20 features computed; none dropped."),
    ("Chi-square test", "Tests independence of cluster vs survival labels.",
     "Validate subgroup-outcome link.", "chi2_contingency; p=0.2546."),
]

PREPROCESSING_DECISIONS = [
    ("Drop ID, Predict labels", "Removed", "ID anonymized; predict columns 100% NaN"),
    ("Missing values", "No imputation", "Zero nulls after column drop"),
    ("Duplicates", "None removed", "0 duplicate rows"),
    ("Outliers", "Retained", "Clinically meaningful extremes"),
    ("Normality transform", "Not applied", "RF rank-invariant; scaler for K-Means"),
    ("Multicollinearity", "Retain all features", "RF subsampling; clinical indices"),
    ("Feature engineering", "None added", "Existing ratios sufficient"),
    ("SMOTE", "Not used", "class_weight preferred"),
    ("RF scaling", "None", "Trees scale-invariant"),
    ("K-Means scaling", "StandardScaler", "Distance-sensitive"),
    ("Train-test split", "80/20 stratified", "702 train / 176 test"),
]
