# -*- coding: utf-8 -*-
"""Slide outline and slide-maker notes for presentation production guide."""

DESIGN_SYSTEM = {
    "font_primary": "Poppins",
    "color_primary": "#1a365d",
    "color_secondary": "#2c5282",
    "color_accent": "#2b6cb0",
    "color_text": "#2d3748",
    "color_muted": "#718096",
    "color_bg_light": "#f7fafc",
    "color_callout": "#ebf8ff",
    "chart_palette": "colorblind-friendly (seaborn colorblind)",
}

GLOBAL_SLIDE_MAKER_RULES = [
    "This document defines STRUCTURE and PRODUCTION NOTES only. Final slide copy, exact wording, and data labels will be added later by the team.",
    "Use Poppins throughout: Bold for titles, SemiBold for section headers, Regular for body. Minimum body size 18pt on slides (this PDF uses smaller type for reference).",
    "Color palette: primary navy #1a365d for titles; secondary #2c5282 for part dividers; accent #2b6cb0 for callouts; white or #f7fafc backgrounds. Avoid red/green-only encoding (colorblind accessibility).",
    "All charts must come from the project figures/ folder at 300 DPI. Do not recreate charts with different numbers or colors.",
    "One main idea per slide. Maximum 5–6 bullet lines per content slide; use speaker notes for detail.",
    "Part divider slides (optional): use full-width band in #2c5282 with white text for PART I–VII transitions.",
    "Always show figure source caption on chart slides: e.g., 'Source: PCSPF Capstone Analysis, n=878'.",
    "Include slide numbers on all slides except title (start numbering at agenda = slide 2).",
    "Preprocessing slides (10–14) are high priority for the professor—use clean tables, generous whitespace, and readable fonts.",
    "Never claim statistical significance where p >= 0.05. Never claim 'excellent' model when AUC = 0.563.",
    "Report legacy f1 tuning (71.02% acc, 0.507 macro F1) alongside primary f1_macro model (61.93%, 0.550).",
    "K-Means slides must state that survival label was NOT used during clustering (only post-hoc overlay).",
    "Appendix slides 31–35: hide in main deck or place after Q&A; link from main slides only if needed.",
]

DELIVERABLES_CHECKLIST = [
    ("Supervised: Random Forest only", "Slides 19–23", "No XGBoost/SVM in main deck"),
    ("Unsupervised: K-Means only", "Slides 15–18", "No DBSCAN in main deck"),
    ("878 patients, 20 features", "Slide 5", "After cleaning 21 cols"),
    ("68.8% majority baseline", "Slides 6, 20, 23", "Must appear before tuned accuracy"),
    ("class_weight balanced", "Slides 6, 14, 19", "Not SMOTE as primary"),
    ("Preprocessing every decision", "Slides 10–13", "Summary slide 13 is anchor"),
    ("19 figures available", "Figure register", "Use mapped filenames"),
    ("Limitations >= 8", "Slide 27", "Honest, numbered"),
    ("Future work >= 8", "Slide 28", "Numbered list"),
    ("Synthesis / bridging", "Slides 24–26", "Core intellectual contribution"),
    ("No data leakage narrative", "Slide 14", "Scaler on full X for K-Means only"),
    ("Chi-square p = 0.2546 honest", "Slide 18", "Do not spin as significant"),
    ("Reproducibility RANDOM_STATE=42", "Slide 14 footnote", "Optional brief mention"),
]

# Each slide: num, title, part, outline_bullets, maker_notes, presenter_notes, figures, layout_hint
SLIDES = [
    {
        "num": 1,
        "title": "Title Slide",
        "part": "Front Matter",
        "outline": [
            "Project title: Pancreatic Cancer Survival Prediction Based on Preoperative Clinical Features",
            "Subtitle: Supervised and Unsupervised Learning Approaches",
            "Course: Fundamentals of Data Science (CMSC 176)",
            "University of the Philippines Manila",
            "Team member names",
            "Date",
        ],
        "maker_notes": "Clean, formal opening. UP Manila branding subtle (logo if allowed). No charts. Dark navy title on white or light background.",
        "presenter_notes": "Introduce team and project in 30 seconds. State that both Random Forest and K-Means were applied to the PCSPF dataset.",
        "figures": [],
        "layout": "Centered title block; logo bottom-right optional.",
    },
    {
        "num": 2,
        "title": "Agenda / Presentation Roadmap",
        "part": "Front Matter",
        "outline": [
            "Visual roadmap or numbered list of all major sections",
            "Gives professor a mental map of the presentation",
        ],
        "maker_notes": "Use horizontal timeline or 7-part icons matching PART I–VII. Match colors to part dividers. Keep text short (7–9 items).",
        "presenter_notes": "Walk through structure in 45 seconds: problem → data → preprocessing → K-Means → RF → synthesis → close.",
        "figures": [],
        "layout": "Roadmap graphic preferred over dense bullet list.",
    },
    {
        "num": 3,
        "title": "Problem Statement and Clinical Background",
        "part": "PART I: Problem Context and Objectives",
        "outline": [
            "Clinical challenge: poor prognosis and high heterogeneity",
            "Preoperative data already collected: tumor markers, nutrition, inflammation, bilirubin",
            "Why stratification matters: surgical planning and supportive care",
            "Feature-domain table mapping 20 PCSPF variables",
            "Research question: predict 1-year survival AND define subgroups",
            "Dual-track scope: RF (supervised) + K-Means (unsupervised) on n=878",
            "Scope boundary: exploratory only, not clinic-ready deployment",
        ],
        "maker_notes": "Left: clinical context + 3 numbered cards + feature-domain table. Right: research question callout, dual-track banner, A/B tracks, scope boundary callout.",
        "presenter_notes": "Emphasize clinical motivation and dual-track question before methods. State explicitly that this is exploratory, not deployment-ready.",
        "figures": [],
        "layout": "Left: clinical cards + feature-domain table; Right: research question, dual-track summary, scope boundary.",
    },
    {
        "num": 4,
        "title": "Project Objectives",
        "part": "PART I",
        "outline": [
            "Primary 1: Supervised classifier (Random Forest) for 1-year survival",
            "Primary 2: Unsupervised clustering (K-Means) for patient subgroups",
            "Primary 3: Synthesize—do same features drive prediction and grouping?",
            "Secondary: Complete reproducible pipeline with documented preprocessing",
        ],
        "maker_notes": "Number objectives 1–4. Use icons: tree (RF), clusters (K-Means), link (synthesis), document (pipeline).",
        "presenter_notes": "Map each objective to later slide numbers so professor sees plan is fulfilled.",
        "figures": [],
        "layout": "2x2 grid of objective cards.",
    },
    {
        "num": 5,
        "title": "Dataset Overview",
        "part": "PART II: Dataset and Exploration",
        "outline": [
            "Source: PCSPF dataset",
            "878 patients; 24 cols → 21 after cleaning (20 features + target)",
            "Feature categories: 2 binary, 18 continuous",
            "Target: 1 = survived >= 1 year, 0 = < 1 year",
            "Dropped: ID, Predict label 1/0 (why)",
        ],
        "maker_notes": "Table layout for feature categories. Small schematic: 24 → drop 3 → 21 columns. No patient-identifiable data.",
        "presenter_notes": "Mention features are z-score standardized in released file if asked.",
        "figures": [],
        "layout": "Summary table + column flow diagram.",
    },
    {
        "num": 6,
        "title": "Target Distribution and Class Imbalance",
        "part": "PART II",
        "outline": [
            "Bar chart: figures/target_distribution.png",
            "604 (68.8%) vs 274 (31.2%); ratio 2.20:1",
            "Majority baseline accuracy = 68.8%",
            "Mitigation: class_weight='balanced'",
        ],
        "maker_notes": "Chart must dominate slide. Annotate bars with counts AND percentages. Footer: baseline accuracy callout in accent box.",
        "presenter_notes": "Explain why accuracy alone is misleading. Preview that F1 and AUC will be reported.",
        "figures": ["figures/target_distribution.png"],
        "layout": "Chart 60% width; bullets right or below.",
    },
    {
        "num": 7,
        "title": "EDA: Feature Distributions and Skewness",
        "part": "PART II",
        "outline": [
            "Histogram grid: figures/feature_distributions.png (or key subset)",
            "Right-skewed: CA19-9, CRP, CEA, bilirubin",
            "D'Agostino-Pearson: most non-normal (p < 0.05)",
            "Decision: no transformation (RF invariant; scaler for K-Means)",
        ],
        "maker_notes": "Full grid may be dense—use 2-slide split OR highlight 4 key panels with callouts. Do not crop in misleading way.",
        "presenter_notes": "Connect skewness to outlier retention decision on slide 11.",
        "figures": ["figures/feature_distributions.png"],
        "layout": "Large figure + 3 short bullets.",
    },
    {
        "num": 8,
        "title": "EDA: Correlation Structure and Multicollinearity",
        "part": "PART II",
        "outline": [
            "Heatmap: figures/correlation_heatmap.png",
            "All feature-target |r| < 0.15",
            "Strong inter-feature correlations (NLR, PLR, SII, CRP/ALB, bilirubin pair)",
            "Implication: need interaction-capable model (RF)",
        ],
        "maker_notes": "Heatmap must be legible—may need landscape slide. Circle or annotate top 3 correlation blocks only.",
        "presenter_notes": "This slide justifies Random Forest over logistic regression.",
        "figures": ["figures/correlation_heatmap.png"],
        "layout": "Full-width heatmap; bullets in footer band.",
    },
    {
        "num": 9,
        "title": "EDA: Class-Conditional Differences",
        "part": "PART II",
        "outline": [
            "Boxplots and/or class-conditional means chart",
            "Largest differences: Abdominal Pain, CA19-9, Prealbumin, inflammatory markers",
            "Differences are modest—weak signal theme",
        ],
        "maker_notes": "Choose ONE primary figure to avoid clutter: class_conditional_means.png preferred for clarity. Optional inset boxplots.",
        "presenter_notes": "Reinforce that univariate separation is weak; multivariate model still warranted.",
        "figures": ["figures/class_conditional_means.png", "figures/boxplots_by_survival.png"],
        "layout": "One main chart + top-5 feature list.",
    },
    {
        "num": 10,
        "title": "Preprocessing: Data Quality Checks",
        "part": "PART III: Preprocessing",
        "outline": [
            "Types: 2 binary int, 18 continuous float64",
            "Missing: zero (3 verification methods)",
            "Duplicates: zero",
            "Data clean—no imputation or deduplication needed",
        ],
        "maker_notes": "Checklist visual with green checkmarks. This slide sets confidence before methodology slides.",
        "presenter_notes": "Speak slowly—professor audits preprocessing carefully.",
        "figures": [],
        "layout": "Three-column checklist.",
    },
    {
        "num": 11,
        "title": "Preprocessing: Outlier and Normality Assessment",
        "part": "PART III",
        "outline": [
            "IQR outlier method on 18 features",
            "Figure: figures/outlier_boxplots.png",
            "Outliers on CA19-9, CRP, CEA, bilirubin—RETAINED (4 reasons)",
            "Normality: D'Agostino-Pearson—most non-normal",
            "No transform applied",
        ],
        "maker_notes": "Split: left = outlier figure; right = decision bullets. Use numbered list for 4 retention reasons.",
        "presenter_notes": "Stress clinical validity of extreme labs—not data errors.",
        "figures": ["figures/outlier_boxplots.png"],
        "layout": "Figure + decision panel.",
    },
    {
        "num": 12,
        "title": "Preprocessing: Multicollinearity (VIF) and Feature Decisions",
        "part": "PART III",
        "outline": [
            "VIF table—top highest scores",
            "Derived ratios correlate with components—expected",
            "All 20 features retained (RF + clinical rationale)",
            "No new feature engineering; no pre-emptive feature drop",
        ],
        "maker_notes": "Table: top 8 VIF features only (appendix has full table). Footnote: K-Means distance limitation acknowledged.",
        "presenter_notes": "Prepare to explain why you did not drop NLR despite high VIF.",
        "figures": [],
        "layout": "VIF table top half; bullet decisions bottom half.",
    },
    {
        "num": 13,
        "title": "Preprocessing: Complete Decision Summary",
        "part": "PART III",
        "outline": [
            "Master table: figures/preprocessing_summary.png",
            "Every row: Step → Action → Justification",
            "Single-reference slide for all preprocessing",
        ],
        "maker_notes": "This slide must be HIGH RES and readable. Consider landscape. This is the professor's anchor slide—do not shrink.",
        "presenter_notes": "Pause here. Offer: 'We can expand any row in Q&A.'",
        "figures": ["figures/preprocessing_summary.png"],
        "layout": "Full-slide table image with minimal overlay text.",
    },
    {
        "num": 14,
        "title": "Train-Test Split and Scaling Strategy",
        "part": "PART III",
        "outline": [
            "80/20 stratified: 702 train / 176 test; random_state=42",
            "Class proportions preserved",
            "StandardScaler for K-Means on full X (878)—NOT for RF",
            "Figure: figures/scaling_before_after.png",
            "class_weight='balanced'",
        ],
        "maker_notes": "Two-column: left = split diagram; right = scaling before/after figure. Include anti-leakage callout box: 'RF trained only on train set; scaler on full X for unsupervised only.'",
        "presenter_notes": "Critical defense slide for data leakage questions.",
        "figures": ["figures/scaling_before_after.png"],
        "layout": "Diagram + figure + callout box.",
    },
    {
        "num": 15,
        "title": "K-Means: Cluster Selection (Elbow + Silhouette)",
        "part": "PART IV: Unsupervised Learning",
        "outline": [
            "Side by side: elbow_method.png, silhouette_scores.png",
            "Silhouette max at k=2; elbow suggests k=3",
            "Chosen k=3: clinical interpretability over pure silhouette",
        ],
        "maker_notes": "Equal-width dual charts. Vertical line at chosen k=3 on both. Caption: 'Target not used in clustering.'",
        "presenter_notes": "Explain trade-off between statistical metric and clinical usefulness.",
        "figures": ["figures/elbow_method.png", "figures/silhouette_scores.png"],
        "layout": "Two charts side by side.",
    },
    {
        "num": 16,
        "title": "K-Means: Cluster Visualization (PCA)",
        "part": "PART IV",
        "outline": [
            "figures/pca_clusters.png",
            "Report PC1 and PC2 variance explained",
            "Note limited 2D variance if applicable",
            "Cluster sizes: 519 (59%), 204 (23%), 155 (18%)",
        ],
        "maker_notes": "Legend must match cluster colors in heatmap slide 17. Mark centroids clearly.",
        "presenter_notes": "Acknowledge PCA is for visualization only—not the clustering space.",
        "figures": ["figures/pca_clusters.png"],
        "layout": "Large scatter plot; size table as inset.",
    },
    {
        "num": 17,
        "title": "K-Means: Cluster Clinical Profiles",
        "part": "PART IV",
        "outline": [
            "figures/cluster_profiles_heatmap.png",
            "Cluster 0: Stable / Low-Risk (lower inflammation, higher prealbumin)",
            "Cluster 1: Hepatobiliary Burden (bilirubin, NLR, SII)",
            "Cluster 2: High-Inflammation (CRP, CRP/ALB, abdominal pain)",
        ],
        "maker_notes": "Three color-coded callout boxes aligned to cluster rows in heatmap. Clinical labels in quotes as phenotype names.",
        "presenter_notes": "Spend 60–90 seconds here—this is the clinical heart of unsupervised section.",
        "figures": ["figures/cluster_profiles_heatmap.png"],
        "layout": "Heatmap + three profile callouts.",
    },
    {
        "num": 18,
        "title": "K-Means: Survival Overlay and Chi-Square",
        "part": "PART IV",
        "outline": [
            "figures/cluster_survival_overlay.png",
            "Survival rates: 70.1%, 69.6%, 63.2%",
            "Chi-square p = 0.2546 — NOT significant at alpha 0.05",
            "Honest interpretation: coherent direction, not conclusive",
        ],
        "maker_notes": "Use neutral colors—not red for 'bad' cluster. Explicitly label p-value on slide. DO NOT use words 'significant' or 'proves.' Optional: Cramér's V if team computes it.",
        "presenter_notes": "Own the non-significance—professor respects honesty. Directional story still valid.",
        "figures": ["figures/cluster_survival_overlay.png"],
        "layout": "Bar chart + p-value callout + 2-line interpretation.",
    },
    {
        "num": 19,
        "title": "Random Forest: Model Setup and Tuning",
        "part": "PART V: Supervised Learning",
        "outline": [
            "Baseline: 100 trees, balanced, 68.18% accuracy",
            "GridSearchCV: three objectives (f1 legacy, f1_macro primary, recall_macro stretch)",
            "Primary best: 100 trees, depth 5, min_samples_leaf 4, min_samples_split 10",
            "Best CV macro F1 0.579 (primary); legacy f1 row kept for comparison",
        ],
        "maker_notes": "Flow diagram: Baseline → GridSearch (3 objectives) → Primary f1_macro model. Tuning comparison table with legacy row footnoted.",
        "presenter_notes": "Lead with f1_macro as primary model. Legacy f1 metrics are reference only — not the deployed RF.",
        "figures": [],
        "layout": "Process flow + parameter table + tuning comparison.",
    },
    {
        "num": 20,
        "title": "Random Forest: Test Set Performance",
        "part": "PART V",
        "outline": [
            "figures/confusion_matrix.png",
            "figures/classification_report.png",
            "Primary f1_macro: 61.93% test acc vs 68.8% baseline (-6.87 pp)",
            "Macro F1 0.550; class-0 recall 36.4% (20/55)",
        ],
        "maker_notes": "Two charts stacked or side by side. Metrics banner across top. Emphasize minority class recall number explicitly.",
        "presenter_notes": "Frame as macro-aligned trade-off: better minority recall, lower accuracy vs baseline. Not breakthrough performance.",
        "figures": ["figures/confusion_matrix.png", "figures/classification_report.png"],
        "layout": "Metrics banner + dual figures.",
    },
    {
        "num": 21,
        "title": "Random Forest: ROC Curve",
        "part": "PART V",
        "outline": [
            "figures/roc_curve.png with AUC = 0.563 (primary f1_macro model)",
            "Above random (0.5) but below typical clinical utility (~0.7)",
            "Lower than legacy f1 tuning (0.613) by design — macro F1 trade-off",
            "Reflects weak preoperative signal—not methodological failure",
        ],
        "maker_notes": "Show diagonal reference line. AUC annotation large and clear. Avoid green 'good' styling.",
        "presenter_notes": "Preempt 'is 0.563 good enough?'—answer honestly. Legacy 0.613 is reference only.",
        "figures": ["figures/roc_curve.png"],
        "layout": "ROC chart dominant; interpretation bullets below.",
    },
    {
        "num": 22,
        "title": "Random Forest: Feature Importance",
        "part": "PART V",
        "outline": [
            "figures/feature_importance.png",
            "Top 5: CEA, Prealbumin, CA19-9, Total Bilirubin, BMI",
            "Brief clinical context per feature",
            "No single dominant predictor",
        ],
        "maker_notes": "Chart on left; 5 compact clinical bullets on right with medical icons optional. Values annotated on bars.",
        "presenter_notes": "Tie back to EDA class-conditional findings where they align.",
        "figures": ["figures/feature_importance.png"],
        "layout": "Chart + clinical sidebar.",
    },
    {
        "num": 23,
        "title": "Performance Context (Honest Transparency)",
        "part": "PART V",
        "outline": [
            "Why performance is modest: |r| < 0.15, missing staging/treatment",
            "Primary AUC 0.563 = signal available from preoperative labs alone",
            "Train 85.8% vs test 61.9% (23.8 pp gap); legacy f1 had 29 pp gap",
            "CV macro F1 0.579 vs test macro F1 0.550 — metric alignment explained",
            "Preempts toughest professor questions",
        ],
        "maker_notes": "This slide should look different—e.g., light gray background, 'Transparency' header. Bullet list only, no charts. Builds trust.",
        "presenter_notes": "Deliver confidently—not apologetically. Primary model metrics only; legacy row in appendix A9.",
        "figures": [],
        "layout": "Text-only transparency slide.",
    },
    {
        "num": 24,
        "title": "Synthesis: Feature Importance vs Cluster Differentiation",
        "part": "PART VI: Synthesis and Bridging",
        "outline": [
            "figures/synthesis_comparison.png",
            "Only CRP/ALB overlaps in both top-5 rankings",
            "RF: tumor/nutrition (CA19-9, CEA, Prealbumin); clusters: inflammation/bilirubin (CRP, SII)",
            "Partial convergence - related biology, different rankings",
        ],
        "maker_notes": "Full-width comparison chart. Highlight CRP/ALB as the sole top-5 overlap; note CA19-9/CEA divergence.",
        "presenter_notes": "Do not say tumor markers define clusters - the chart shows the opposite for CA19-9 (#15) and CEA (#20).",
        "figures": ["figures/synthesis_comparison.png"],
        "layout": "Comparison figure + overlap callout.",
    },
    {
        "num": 25,
        "title": "Synthesis: Predicted Probability per Cluster",
        "part": "PART VI",
        "outline": [
            "Table: Cluster | N | Actual survival % | Mean predicted % | Difference",
            "Does model confidence track cluster structure?",
            "Directional alignment despite modest AUC",
        ],
        "maker_notes": "Clean table design—team fills numbers from notebook. Heat-map conditional formatting optional for Difference column.",
        "presenter_notes": "Even modest AUC can show coherent ranking across clusters.",
        "figures": [],
        "layout": "Table-centric slide.",
    },
    {
        "num": 26,
        "title": "Synthesis: Clinical Narrative",
        "part": "PART VI",
        "outline": [
            "Single convergence paragraph (provided in outline)",
            "Unsupervised + supervised point same direction",
            "Modest but mutual validation",
        ],
        "maker_notes": "Text-only slide. Use pull-quote styling for key sentence. Maximum 120 words on slide—rest in speaker notes.",
        "presenter_notes": "Read or paraphrase carefully—most important paragraph of presentation.",
        "figures": [],
        "layout": "Large pull-quote / narrative block.",
    },
    {
        "num": 27,
        "title": "Limitations",
        "part": "PART VII: Limitations, Future Work, Conclusion",
        "outline": [
            "At least 8 limitations",
            "Categories: data, model, analysis",
            "Include: imbalance, weak correlations, no external validation, K-Means assumptions, multicollinearity, chi-square n.s., missing staging",
        ],
        "maker_notes": "Two-column numbered list. Icons per category. Do not crowd—use 8–10 clear lines.",
        "presenter_notes": "Show scientific maturity. Invite questions on any limitation.",
        "figures": [],
        "layout": "Categorized bullet columns.",
    },
    {
        "num": 28,
        "title": "Future Work",
        "part": "PART VII",
        "outline": [
            "At least 8 directions",
            "XGBoost/SVM, DBSCAN, transforms, SHAP, SMOTE compare, external validation, staging features, Cox/KM",
        ],
        "maker_notes": "Numbered list with forward-arrow icons. Lighter visual weight than limitations slide.",
        "presenter_notes": "Connect each item to a limitation where possible.",
        "figures": [],
        "layout": "Numbered list, single column.",
    },
    {
        "num": 29,
        "title": "Conclusion",
        "part": "PART VII",
        "outline": [
            "RF (f1_macro tuned): 61.93% test accuracy, AUC 0.563, macro F1 0.550",
            "Top features: CA19-9, CEA, Prealbumin, CRP/ALB, BMI",
            "K-Means: 3 clusters, Cluster 2 lowest survival (63.2%)",
            "Convergence on inflammation/tumor markers",
            "Preoperative labs alone are limited—need staging/treatment",
        ],
        "maker_notes": "Four takeaway blocks with icons. Mirror notebook Section 9 metrics exactly.",
        "presenter_notes": "60-second close. Do not introduce new claims.",
        "figures": [],
        "layout": "Four quadrant takeaways.",
    },
    {
        "num": 30,
        "title": "Thank You and Q&A",
        "part": "Front Matter",
        "outline": [
            "Clean closing",
            "Team names",
            "Questions and Discussion",
        ],
        "maker_notes": "Minimal design matching title slide. QR to notebook/repo optional if allowed.",
        "presenter_notes": "Point to appendix slides for detailed tables if questions arise.",
        "figures": [],
        "layout": "Centered thank you + team names.",
    },
]

APPENDIX_SLIDES = [
    (31, "Full Preprocessing Summary Table", "Backup detail for Q&A", ["figures/preprocessing_summary.png"]),
    (32, "Full Classification Report Table", "Per-class precision/recall/F1", ["figures/classification_report.png"]),
    (33, "VIF Table", "All 20 features", []),
    (34, "Normality Test Results", "D'Agostino-Pearson all features", []),
    (35, "Outlier Summary Table", "IQR counts per feature", []),
]

PARTS_ORDER = [
    ("Front Matter", "Slides 1–2"),
    ("PART I: Problem Context and Objectives", "Slides 3–4"),
    ("PART II: Dataset and Exploration", "Slides 5–9"),
    ("PART III: Preprocessing", "Slides 10–14"),
    ("PART IV: Unsupervised (K-Means)", "Slides 15–18"),
    ("PART V: Supervised (Random Forest)", "Slides 19–23"),
    ("PART VI: Synthesis", "Slides 24–26"),
    ("PART VII: Close", "Slides 27–30"),
    ("APPENDIX (Q&A backup only)", "Slides 31–35"),
]

TIMING_GUIDE = [
    ("Front Matter", "1–2", "1.5 min"),
    ("PART I", "3–4", "2 min"),
    ("PART II", "5–9", "5 min"),
    ("PART III", "10–14", "6 min"),
    ("PART IV", "15–18", "5 min"),
    ("PART V", "19–23", "7 min"),
    ("PART VI", "24–26", "4 min"),
    ("PART VII", "27–30", "4 min"),
    ("Total (main deck)", "1–30", "~34–38 min"),
]
